language: ruby
rvm:
  - 2.2.4
gemfile:
  - Gemfile
services:
  - postgresql
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake test
before_script:
  - psql -c 'create database timmy_test' -U postgres
