default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  user: postgres
  password:

development:
  <<: *default
  database: timmy_development

test:
  <<: *default
  database: timmy_test

production:
  <<: *default
  database: timmy_production
  username: timmy
  password: <%= ENV['TIMMY_DATABASE_PASSWORD'] %>
